{% set version = "0.1.0a" %}

package:
  name: odm2rest
  version: {{ version }}

source:
  # not useing the jinja variable for the version b/c the release is not pep440
  # see https://www.python.org/dev/peps/pep-0440/#id25
  url: https://github.com/ODM2/ODM2RESTfulWebServices/archive/v0.1.0-alpha.tar.gz
  sha256: f79d94dd58e7ed0e223049067bfc9e1d98234bca9ddf65bfd9eb62ff14d2a8bf

build:
  number: 0
  skip: True  # [py3k]
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - django 1.11.*
    - jsonschema
    - odm2api 0.7.*
    - pandas
    - python
    - sqlalchemy
    - djangorestframework 3.6.4
    - djangorestframework-csv
    - djangorestframework-xml
    - djangorestframework-yaml

test:
  imports:
    - odm2rest

about:
  home: https://github.com/ODM2/ODM2RESTfulWebServices/
  license: BSD 3-Clause
  license_file: LICENSE
  summary: "A  Python RESTful web service inteface for accessing data in an ODM2 database via Django rest swagger APIs."

extra:
  recipe-maintainers:
    - lsetiawan
    - emiliom
    - ocefpaf
