language: generic

os:
  - osx
  - linux

sudo: false

env:
  global:
    secure: "rYNkVLys5dnhyIkng21hm3Z4Locs698ZhKussNMe/IpQyUf5PdXppEFmeRYCmxSUuOzHSjyfDdm9eX9WJxNyPe11mn/aLFjVl+K2XRKUhRyBO1OeeFO+dtjgiQTLP1KQfUhZ6rYsI//3eylqmxRMUULIz7LKSZrtMUByd4jC5EZhyIN5X2bPkLK/5Jcm2Bh4FAHVEfyIpDvbw/GJmPVGg2REH9D10l1FYbiJuaLO4t6UT94EH8HUil2o8jaujWI8iui/AnXmqh+hrmy1Z99Drs3tm3m3nNtuFoWiKmSewSLAGYdTpXFFPDYq/onaP+5Pu1sN6m5ga7lOGV+UjIt2sZEc3JHqn4yFH4Z2zJf+H08+rscH33zEkYiocdCaqxtuGJ7jMMsV2aXhkRm8aofXzE8OWIjh1iGR9uWgr4VhsplqoGbowYwwAfas/Ebs4YzQehc5gXAj/EJH8aE+HxKVs7+XGBVYiQUF54wd+W7dW2uc1N50XdLh8LB+RD5xgK5VkApQlVWlLX9Pt5v/mB1cYrT+PIp+Uninw7csuGY1XnpddcLE/Eu4KXWSn1RCpo9hStoRSdVHYGrVGl3QVn3sEOt3FbMTEkk43iPDhS57ET03Xx/aoMCReF+uJAInghFHhyeE6DUcCBpMrjMQjn+7SkeTv0CFxrydLzW6waJG1dk="

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
       brew remove --ignore-dependencies --force $(brew list) ;
    fi

install:
  # Install miniconda.
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then URL="https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh" ; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then URL="https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh" ; fi
  - curl -L $URL -o miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no --set show_channel_urls true --set auto_update_conda false
  - conda config --set show_channel_urls true
  #- conda update --quiet conda

  # This numpy variable is not used, but conda-build complains if we haven't set it already.
  - export CONDA_NPY=19
  - conda config --add channels odm2
  - conda install conda-build-all
  - conda install conda=4.2.16  # Temporary workaround for a bug in conda-build-all.
  - conda info

  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      conda env create --file environment.yml ;
      source activate ODM2 ;
    fi

script:
  - if [[ "$BINSTAR_TOKEN" == "" ]]; then
      export UPLOAD="";
    else
      export UPLOAD="--upload-channels odm2";
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      conda-build-all ./recipes $UPLOAD --inspect-channels odm2 --matrix-conditions "numpy >=1.12" "python >=2.7,<3|>=3.5,<=3.6" ;
    fi

  # Packages integration tests via user notebooks.
  - if [[ "$TEST_TARGET" == "linux" ]]; then
      cd tests && python test_notebooks.py ;
    fi
