language: generic

os: osx

sudo: false

env:
  global:
    secure: "ZnEdu0lLBRXVLnqSU9duTu+IjSnPs0YOkfvcyspbpI8OewCx+g5DiWRCjcU9GOGscoYoMdTUOwh/E6CloEhAlxaOxtAK4yKFhewu2bUwnZTWwoL+AL9pJZ9z1jUHAU5asAcganYP691g0YO/O9y7h2OedGrmAjDSigdAHE/FtgBuXANfJAIN78cP899XwYQyWYZmeLNtWTKD2kpKv1Z6Y5ivp7cmjn19wwLJekShNMEe2CiTY44rkwwHXNPuoKELQZEE+8TJdFbLm7rh5weucOqtvWuXr0BFS9Kbw/SLKZUWfnrZ9GttNRE7Gi+R/NhXWRIZw4rSkl0njw4jFu/tmojHDAq874hEWqLIjrdrWAqs9ee3JmfcyQQzWPiGIlshiilPC/nyV7Oo45RlPZiceMac5u05kjA1WLGzXnHHdQmfZ8/M7szGLN+jmFE0vYajM9mYihKWhQpIkPVVIEe2k6eRt06zoBqAP4yP/9SIOgW4ik+gwnCWflNEA2vGZV2+s+5KQ7Q8FB+9XjghUY8LooUNGkzasy7vjizaOIt4c2fC3cYQB2Lxhf0L6ulhB7v/u4SSi55bjGm3vI/SNA0pbXVFVaclsaBuTV4dLItRpjyy0quNPdji2oQEBKW58R9rB8Kv7YcHyv2ozty40p5nMutoWWQ3wy2BgsYkxWVcaY4="

before_install:
  - brew remove --ignore-dependencies --force $(brew list)

install:
  # Install miniconda.
  - curl -O https://raw.githubusercontent.com/pelson/Obvious-CI/master/bootstrap-obvious-ci-and-miniconda.py
  - python bootstrap-obvious-ci-and-miniconda.py ~/miniconda x64 2 --without-obvci && source ~/miniconda/bin/activate root

  # This numpy variable is not used, but conda-build complains if we haven't set it already.
  - export CONDA_NPY=19

  - conda config --set show_channel_urls true
  - conda config --add channels odm2
  - conda install --yes -c odm2 -c conda-forge obvious-ci conda-build-all
  - obvci_install_conda_build_tools.py

  # Temporary workaround to bootstrap latest conda-build-all.
  - conda install --yes conda-build=2.0.10
  - conda install --yes conda==4.2.13

  - conda info

script:
  - if [[ "$BINSTAR_TOKEN" == "" ]]; then
      export UPLOAD="";
    else
      export UPLOAD="--upload-channels odm2";
    fi
  - conda-build-all ./recipes $UPLOAD --inspect-channels odm2 --matrix-conditions "numpy >=1.11" "python >=2.7,<3|>=3.5,<=3.6"
