{% set version="2.1.3" %}

package:
  name: gitpython
  version: {{ version }}

source:
  fn: GitPython-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/G/GitPython/GitPython-{{ version }}.tar.gz
  sha256: 3826185b11e1fc372e7d31251e9b65e11ccb7c27f82c771d619048bdb5b66c81

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - gitdb >=0.6.4

test:
  imports:
    - git
    - git.index
    - git.objects
    - git.objects.submodule
    - git.refs
    - git.repo

about:
  home: https://github.com/gitpython-developers/GitPython
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Python Git Library'
  doc_url:  http://gitpython.readthedocs.org

extra:
  recipe-maintainers:
    - ocefpaf
