{% set version = "0.4.2" %}

package:
  name: valideer
  version: {{ version }}

source:
  fn: valideer-{{ version }}.tar.gz
  url: https://github.com/podio/valideer/archive/{{ version }}.tar.gz
  sha256: be554a6f93eab049dd419a181c409a2e6421696263c7eb472cbdfaa46df9d1b1

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - decorator

test:
  imports:
    - valideer
    - valideer.tests

about:
  home: https://github.com/podio/valideer
  license: MIT
  summary: 'Lightweight data validation and adaptation library for Python.'

extra:
  recipe-maintainers:
    - ocefpaf
    - emiliom
