{% set version = "1.0.2" %}

package:
  name: conda-build-all
  version: {{ version }}

source:
    fn: conda-build-all_v{{ version }}.tar.gz
    url: https://github.com/SciTools/conda-build-all/archive/v{{version}}.tar.gz
    sha256: 5b22fb3e427852d22db35902f8d833beaecb1a5ec99aaf7fa6c9acfb324ced06

build:
  number: 0
  skip: True  # [py36]
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - conda-build-all = conda_build_all.cli:main

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - gitpython
    - conda >4
    - conda-build >=1.21.7
    - anaconda-client
    - mock

test:
  imports:
    - conda_build_all
  commands:
    - conda build-all --version

about:
  home: https://github.com/scitools/conda-build-all
  license: BSD 3-clause
  license_file: LICENSE
  summary: conda build-all is a conda subcommand which allows multiple distributions to be built (and uploaded) in a single command

extra:
  recipe-maintainers:
    - ocefpaf
