{% set version = "1.1.3" %}

package:
  name: conda-build-all
  version: {{ version }}

source:
  url: https://github.com/conda-forge/conda-build-all/archive/v{{version}}.tar.gz
  sha256: e296f5eebae17f6a5ee90af9c2838fb5241656509cd008375f4bfbd704f53da8

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - conda-build-all = conda_build_all.cli:main

requirements:
  build:
    - python
    - pip
  run:
    - python
    - gitpython
    - conda >=4.2
    - conda-build >=1.21.7
    - anaconda-client
    - mock

test:
  imports:
    - conda_build_all
  commands:
    - conda build-all --version

about:
  home: https://github.com/scitools/conda-build-all
  license: BSD 3-clause
  license_file: LICENSE
  summary: 'conda build-all is a conda subcommand which allows multiple distributions to be built (and uploaded) in a single command.'

extra:
  recipe-maintainers:
    - ocefpaf
