{% set version = "0.6.0" %}

package:
  name: odm2api
  version: {{ version }}.a0

source:
  fn: odm2api-v{{ version }}-alpha.tar.gz
  url: https://github.com/ODM2/ODM2PythonAPI/archive/v{{ version }}-alpha.tar.gz
  sha256: 13597f1b2b8fc74ea9e7c18ce85fffac5e60ff3b1eaf1ab0ca92a281211aa2bc

build:
  number: 0
  skip: True  # [py3k]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - pyodbc
    - pymysql
    - sqlalchemy
    - geoalchemy-odm2
    - shapely
    - pandas
    - psycopg2
    - six

test:
  imports:
    - odm2api

about:
  home: https://github.com/ODM2/ODM2PythonAPI
  license: BSD 3-Clause
  license_file: LICENSE
  summary: "A Python-based application programmer's interface for the Observations Data Model 2 (ODM2)."

extra:
  recipe-maintainers:
    - ocefpaf
    - emiliom
