{% set version = "2.0.11b0" %}

package:
  name: wofpy
  version: {{ version }}

source:
  fn: WOFpy-{{ version }}.tar.gz
  url: https://github.com/ODM2/WOFpy/archive/{{ version }}.tar.gz
  sha256: 984452fb7852c0aeb5a7ffeb9174d703f53ed2f71e210d933deb4132b3c6eadc

build:
  number: 0
  skip: True  # [py3k]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - flask
    - lxml
    - spyne
    - python-dateutil
    - jinja2
    - pytz

test:
  imports:
    - examples
    - examples.flask
    - examples.flask.barebones
    - examples.flask.barebones.tests
    - examples.flask.cbi
    - examples.flask.csv_server
    - examples.flask.csv_tutorial
    - examples.flask.csv_tutorial.solution
    - examples.flask.csv_tutorial.tutorial
    - examples.flask.odm2
    - examples.flask.odm2.measurement
    - examples.flask.odm2.timeseries
    - examples.flask.odm_1_1
    - examples.flask.swis
    - wof
    - wof.apps
    - wof.flask

about:
  home: https://github.com/ODM2/WOFpy
  license: BSD 3-Clause
  summary: 'Serve WaterOneFlow web services.'

extra:
  recipe-maintainers:
    - ocefpaf
    - emiliom
