{% set version = "2.0.10b0" %}

package:
  name: wofpy
  version: {{ version }}

source:
  fn: WOFpy-{{ version }}.zip
  url: https://pypi.io/packages/source/W/WOFpy/WOFpy-{{ version }}.zip
  sha256: a159c47a4db1610b1925fe7e508347fa603fd9fa53f95be183c7878833f76712

build:
  number: 0
  skip: True  # [py3k]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - flask
    - lxml
    - spyne
    - python-dateutil
    - jinja2
    - pytz

test:
  imports:
    - examples
    - examples.flask
    - examples.flask.barebones
    - examples.flask.barebones.tests
    - examples.flask.cbi
    - examples.flask.csv_server
    - examples.flask.csv_tutorial
    - examples.flask.csv_tutorial.solution
    - examples.flask.csv_tutorial.tutorial
    - examples.flask.odm2
    - examples.flask.odm2.measurement
    - examples.flask.odm2.timeseries
    - examples.flask.odm_1_1
    - examples.flask.swis
    - wof
    - wof.apps
    - wof.flask

about:
  home: https://github.com/ODM2/WOFpy
  license: BSD 3-Clause
  summary: 'Serve WaterOneFlow web services.'

extra:
  recipe-maintainers:
    - ocefpaf
    - emiliom
