{% set version = "0.1.0" %}

package:
    name: odm2api
    version: {{ version }}.a0

source:
    git_url: https://github.com/ODM2/ODM2PythonAPI.git
    git_tag: v{{ version }}-alpha

build:
    number: 0
    skip: True  # [py3k]
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - pyodbc
        - pymysql
        - sqlalchemy
        - geoalchemy-odm2
        - shapely
        - pandas
        - psycopg2  # [not win]
        - six

test:
    imports:
        - odm2api

about:
    home: https://github.com/ODM2/ODM2PythonAPI
    license: Open GPL
    summary: A Python-based application programmer's interface for the Observations Data Model 2 (ODM2)

extra:
    recipe-maintainers:
        - ocefpaf
        - emiliom
