{% set version = "2.12.13" %}

package:
  name: spyne
  version: {{ version }}

source:
  fn: spyne-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/s/spyne/spyne-{{ version }}.tar.gz
  sha256: 0aa5d4ba239555c4640080199fdbad1567efd503e936ca9b809f198a529a111a

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - sort_wsdl=spyne.test.sort_wsdl:main

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - pytz
    - lxml  # [not osx]
    - zope.interface
    - sqlalchemy <1.0.99
    - pyzmq
    - werkzeug
    - pyparsing
    - twisted
    - django
    - pyramid
    - msgpack-python
    - pyyaml
    - simplejson
    - pywin32  # [win and py2k]

test:
  imports:
    - spyne
    - spyne.auxproc
    - spyne.client
    - spyne.client.twisted  # [not py3k]
    - spyne.const
    - spyne.interface
    - spyne.interface.wsdl  # [not osx]
    - spyne.interface.xml_schema  # [not osx]
    - spyne.model
    - spyne.model.primitive
    - spyne.protocol
    - spyne.protocol.cloth  # [not osx]
    - spyne.protocol.dictdoc
    - spyne.protocol.html  # [not osx]
    - spyne.protocol.soap  # [not osx]
    - spyne.server
    - spyne.server.twisted  # [not py3k]
    - spyne.store
    - spyne.store.relational
    - spyne.test
    - spyne.test.interface
    - spyne.test.interface.wsdl  # [not osx]
    - spyne.test.interop
    - spyne.test.interop.server
    - spyne.test.interop.server.soap11
    - spyne.test.interop.server.soap12
    - spyne.test.model
    - spyne.test.multipython
    - spyne.test.multipython.model
    - spyne.test.protocol
    - spyne.test.transport
    - spyne.util
    - spyne.util.oset

about:
  home: http://spyne.io
  license: LGPL-2.1
  summary: 'A transport and architecture agnostic rpc library that focuses on exposing public services with a well-defined API.'

extra:
  recipe-maintainers:
    - ocefpaf
    - emiliom
