{% set version="2.6.0" %}

package:
  name: python-dateutil
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/python-dateutil/python-dateutil-{{ version }}.tar.gz
  sha256: 62a2f8df3d66f878373fd0072eacf4ee52194ba302e00082828e0d263b0418d2

build:
  number: 1
  skip: True  # [win or osx]
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - six

test:
  imports:
    - dateutil
    - dateutil.rrule

about:
  home: https://dateutil.readthedocs.org/
  license: BSD 3-clause
  license_file: LICENSE
  summary: 'Extensions to the standard Python datetime module.'
  description: |
    The dateutil module provides powerful extensions to the standard datetime
    module, available in Python.
  doc_url: https://dateutil.readthedocs.org/en/latest/
  dev_url: https://github.com/dateutil/dateutil/

extra:
  recipe-maintainers:
    - ocefpaf
    - emiliom
