{% set version = "2.0.15" %}

package:
  name: uwsgi
  version: {{ version }}

source:
  fn: uwsgi-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/u/uWSGI/uwsgi-{{ version }}.tar.gz
  sha256: 572ef9696b97595b4f44f6198fe8c06e6f4e6351d930d22e5330b071391272ff

build:
  number: 0
  skip: True  # [win]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - python
    - libxml2  # [not win]
    - openssl 1.0.*
    - pcre
    - yaml
    - zlib 1.2*
  run:
    - python
    - libxml2  # [not win]
    - openssl 1.0.*
    - pcre
    - yaml
    - zlib 1.2*

test:
  source_files:
    - tests
  commands:
    - uwsgi --version

about:
  home: https://github.com/unbit/uwsgi
  license: GPL-2.0
  license_file: LICENSE
  summary: "The uWSGI full stack for building hosting services."

extra:
  recipe-maintainers:
    - ocefpaf
